// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATQtDYMSq_xpOgvC6JbnJxGn02GX0RzzE',
    appId: '1:616913199124:web:dacda1edbd09ec7c168701',
    messagingSenderId: '616913199124',
    projectId: 'flutter-step-tracking',
    authDomain: 'flutter-step-tracking.firebaseapp.com',
    storageBucket: 'flutter-step-tracking.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH5sbhEHrMZ4ssmoYUOK71Q2uSjpYBR9s',
    appId: '1:616913199124:android:cb97dc6f534f1357168701',
    messagingSenderId: '616913199124',
    projectId: 'flutter-step-tracking',
    storageBucket: 'flutter-step-tracking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJwpxH1EFyO0CBrPMBG160oArEjn_fXyk',
    appId: '1:616913199124:ios:733e4def00b518af168701',
    messagingSenderId: '616913199124',
    projectId: 'flutter-step-tracking',
    storageBucket: 'flutter-step-tracking.appspot.com',
    iosBundleId: 'com.example.flutterStepTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJwpxH1EFyO0CBrPMBG160oArEjn_fXyk',
    appId: '1:616913199124:ios:733e4def00b518af168701',
    messagingSenderId: '616913199124',
    projectId: 'flutter-step-tracking',
    storageBucket: 'flutter-step-tracking.appspot.com',
    iosBundleId: 'com.example.flutterStepTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATQtDYMSq_xpOgvC6JbnJxGn02GX0RzzE',
    appId: '1:616913199124:web:4b433a86f2e1899e168701',
    messagingSenderId: '616913199124',
    projectId: 'flutter-step-tracking',
    authDomain: 'flutter-step-tracking.firebaseapp.com',
    storageBucket: 'flutter-step-tracking.appspot.com',
  );
}
